# Generated by Django 3.2.16 on 2025-04-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250413_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, null=True, upload_to='users/images', verbose_name='Аватар'),
        ),
    ]
