# Generated by Django 3.2.16 on 2025-04-16 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Username is not valid', regex='^[\\w.@+-]+$')], verbose_name='Логин'),
        ),
    ]
